blog/urls.py
from django.urls import path
from .views import post_detail,  post_share, post_list

app_name = 'blog'

urlpatterns = [
    path('', post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),
    # path('', PostListView.as_view(),name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:posti>/', post_detail, name='post_detail'),    
    path('<int:post_id>/share/', post_share, name='post_share')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse 
from taggit.managers import TaggableManager

# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')




class Post(models.Model):
    STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'),)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    class Meta:
        ordering= ('-publish',)

    def __str__(self):
        return self.title

    # objects = models.Manager() #el manager por defecto
    # published = PublishedManager() #el manager personalizado


    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,self.publish.month,self.publish.day,self.slug])

    tags = TaggableManager()
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f"Comentario por {self.name} en {self.post}"

blog/forms.py
from django import forms

from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail


from .forms import EmailPostForm, CommentForm
from .models import Post, Comment

from taggit.models import Tag

# Create your views here.


# class PostListView(ListView):
#     queryset = Post.objects.filter(status='published')
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    object_list = Post.objects.filter(status='published')
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3) #3 post por página
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        #si la página no es un integer reparte la primera página
        posts = paginator.page(1)
    except EmptyPage:
        # si la página está fuera de rango, reparte la última página
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {
        'page': page,
        'posts': posts,
        'tag': tag
    })

def post_detail(request, year, month, day, posti):
    post = get_object_or_404(Post, slug=posti,
                                    status='published',
                                    publish__year=year,
                                    publish__month=month,
                                    publish__day=day)
    # Lista de comentarios activos para este post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # un comentario ha sido posteado
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # crea un objeto comentario pero no lo guarda en la base de datos aun
            new_comment = comment_form.save(commit=False)
            #Asigna el post actual al comentario
            new_comment.post = post
            # Guarda el comentario en la bas de datos
            new_comment.save()
    else:
        comment_form = CommentForm()

    #Lista de posts similares
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects.filter(status='published', tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', 'publish')[:2]

    return render(request,'blog/post/detail.html',{
        'post': post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'similar_posts': similar_posts
        })


def post_share(request, post_id):
    #recupera el post por el id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False


    if request.method == 'POST':
        #el form fue recibido
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # el form pasó las validaciones
            cd  = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} te recomienda que leas {post.title}"
            message = f"Leer {post.title} en {post_url}\n\n" \
                       f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'daluz0221@gmail.com', [cd['to']])
            sent = True
            #...se envía el email
    else:
        form = EmailPostForm()
        
    return render(request, 'blog/post/share.html', {
            'post':post, 
            'form': form,
            'sent':sent
            }) 

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}
      
    {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>
    <div id="content">
        {% block content %}
          
        {% endblock content %}
    </div>
    <div id="sidebar">
        <h2>Mi blog</h2>
        <p>Este es mi blog. He escrito {% total_posts %} posts hasta el momento</p>
        <h3>Últimos post</h3>
        {% show_latest_posts 3 %}
        <h3>Posts más comentados</h3>
        {% get_most_coment_post as most_commented %}
        <ul>
            {% for post in most_commented %}
                <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}


{% block title %}
  {{ post.title }}
{% endblock title %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Publicado {{ post.published }} por {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
      <a href="{% url 'blog:post_share' post.id %}">
        Compartir este post
      </a>
    </p>
    <h2>Post similares</h2>
    {% for post in similar_posts %}
      <p>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </p>
    {% empty %}
      No hay posts similares
    {% endfor %}
    {% with comments.count as total_comments %}
      <h2>
        {{ total_comments }} comentario{{ total_comments|pluralize }}
      </h2>
    {% endwith %}
    
    {% for comment in comments %}
      <div class="comment">
        <p class="info">
          Comentario {{ forloop.counter }} por {{ comment.name }}
          {{ comment.created }}
        </p>
        {{ comment.body|linebreaks }}
      </div>
    {% empty %}
      <p>No hay comentarios todavía</p>
    {% endfor %}
    {% if new_comment %}
      <h2>Tu comentario ha sido agregado!</h2>
    {% else %}
      <h2>Agrega un nuevo comentario</h2>
      <form method="post">
        {{ comment_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Agregar comentario"></p>
      </form>
    {% endif %}
{% endblock content %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in l_post %}
      <li><a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a></li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}
  Mi Blog
{% endblock title %}

{% block content %}
  <h1>Mi Blog</h1>
  {% if tag %}
    <h2>Posts etiquetados con "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
    <h2>
        <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
            
        </a>
    </h2>
    <p class="tags">
      Etiquetas: 
      {% for tag in post.tags.all %}
        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
          {{ tag.name }}
        </a>
        {% if not forllop.last %}
          ,
        {% endif %}
      {% endfor %}
    </p>
    <p class="date">
        Publicado {{ post.publish }} por {{ post.author }}
    </p>
    {{ post.body|markdown|truncatewords_html:20 }}
  {% endfor %}
  {% include "pagination.html" with page=posts %}
{% endblock content %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}
  Compartir un post
{% endblock title %}

{% block content %}
    {% if sent %}
      <h1>Correo enviado con éxito</h1>
      <p>
          "{{ post.title }}" fue enviado con éxtio a {{ form.cleaned_data.to }}.
      </p>
    {% else %}
      <h1>Compartir "{{ post.title }}" por correo</h1>
      <form method="post">
          {{ form.as_p }}
          {% csrf_token %}
          <input type="submit" value="Enviar correo">
      </form>
    {% endif %}
{% endblock content %}

blog/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Anterior</a>
    {% endif %}

    <span class="current">
      Página {{ page.number }} de {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Siguiente</a>
    {% endif %}
  </span>
</div>